//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webform_postilion.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class postilion_role
    {
        public int id { get; set; }
        public string action { get; set; }
        public int branch_users { get; set; }
        public int convenience_users { get; set; }
        public int C099_MICROPLAN_FINANCIAL_SERVICES { get; set; }
        public int C051_TREASURY_DEPARTMENT { get; set; }
        public int C013_KWEKWE_BRANCH { get; set; }
        public int C870_BS_BULAWAYO_BRANCH { get; set; }
        public int C882_BS_GWERU_BRANCH { get; set; }
        public int C016_CENTRAL_CASH_DEPOT { get; set; }
        public int C006_BATANAI_GARDENS_BRANCH { get; set; }
        public int C055_TRADE_FINANCE_DEPARTMENT { get; set; }
        public int C864_BS_TREASURY_BRANCH { get; set; }
        public int C860_BS_REGIONAL_OFFICE { get; set; }
        public int C020_FBC_CENTRE_BRANCH { get; set; }
        public int C850_BANK_REGIONAL_OFFICE { get; set; }
        public int C861_BS_LEOPOLD_TAKAWIRA_BRANCH { get; set; }
        public int C027_BORROWDALE_BRANCH { get; set; }
        public int C005_JASON_MOYO_STREET_BRANCH { get; set; }
        public int C001_SAMORA_MACHEL_AVENUE_BRANCH { get; set; }
        public int C000_HEAD_OFFICE_BRANCH { get; set; }
        public int C009_MUTARE_BRANCH { get; set; }
        public int C007_CUSTODIAL_SERVICES { get; set; }
        public int C880_BS_MUTARE_BRANCH { get; set; }
        public int C029_FBC_BUSINESS_BANKING_DIVISION { get; set; }
        public int C008_ZVISHAVANE_BRANCH { get; set; }
        public int C012_VICTORIA_FALLS_BRANCH { get; set; }
        public int C026_BEITBRIDGE_BRANCH { get; set; }
        public int C011_CHINHOYI_BRANCH { get; set; }
        public int C866_BS_PROJECTS__BRANCH { get; set; }
        public int C018_BULAWAYO_CENTRAL_CASH { get; set; }
        public int C028_GRANITE_SIDE_BRANCH { get; set; }
        public int C014_MASVINGO_BRANCH { get; set; }
        public int C010_GWERU_BRANCH { get; set; }
        public int C002_NELSON_MANDELA_AVENUE_BRANCH { get; set; }
        public int C883_BS_KWEKWE_BRANCH { get; set; }
        public int C863_BS_MORTGAGES_BRANCH { get; set; }
        public int C862_BS_FBC_CENTRE_BRANCH { get; set; }
        public int C881_BS_MASVINGO_BRANCH { get; set; }
        public int C021_MSASA_BRANCH { get; set; }
        public int C019_CONVENIENCE_BANKING_BRANCH { get; set; }
        public int C003_SOUTHERTON_BRANCH { get; set; }
        public int C865_BUSINESS_BANKING_BRANCH { get; set; }
        public int C004_FBC_PRIVATE_BANK__HARARE { get; set; }
        public int C022_CHITUNGWIZA_BRANCH { get; set; }
        public int C015_CENTRAL_PROCESSING_CENTRE { get; set; }
        public int C017_BULAWAYO_PRIVATE__BANKING_CENTRE { get; set; }
        public int C030_HEAD_OFFICE_BRANCH { get; set; }
        public int C031_CORPORATE_AND_INSTITUTIONAL_BANKING { get; set; }
        public int C960_BUREAU_DE_CHANGE_REGIONAL_OFFICE { get; set; }
        public int C961_KWAME_NKRUMAH_BUREAU_DE_CHANGE { get; set; }
        public int C962_JASON_MOYO_BUREAU_DE_CHANGE { get; set; }
        public int C964_KWAME_NKRUMAH_BUREAU_DE_CHANGE { get; set; }
        public int C032_FBC_VIRTUAL { get; set; }
    }
}
